title: Streamvar Analytics
lang: en
description: Opinionated github flavored standard document theme for open source projects, with few options, but everything!

theme: null

# debug:
#   compress: false
#   dist: false
#   extension: true

readme_index:
  with_frontmatter: true

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - icons=font

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-redirect-from
exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
