=== Environment dependencies
*   JDK 1.8 or above
[NOTE]
The jar command must be invokable from your shell. This amounts to having the JDK in your path.
* Git Bash on windows System.

=== Stream Engine

.To run with stream engine

* Download the zip.
* Unzip the distribution(AW) using the following command

	unzip streamvar-mdk-aw-<version>.zip

TIP: To execute scripts from anywhere, MDK directory can be added to the PATH variable.

* Build the Stream Var model against a pre-packaged example configuration/json dataset. To do so execute –

	bash build_mar -c examples/sv_dsl.json.everyinput.feature

    Command Line Arguments
    usage: bash build_mar -c <stream var config file>
    required arguments:
        -c      stream var Config File
    optional arguments:
        -h      Show this help message
        -m      StreamVar model mar name

* This should build the StreamVar mar and place it the current directory. Default mar name is stream-var-model.mar

* You can create the model with different name by supplying the argument *-m <model name>* in the above command
* To run the StreamVar model against an input dataset
	
    bash execute_mar -r streamEngine -m stream-var-model.mar -i examples/input_with_var_requests.jsonl -d driver.inmemory.conf -o output.jsonl

    Command Line Arguments
    usage: bash execute_mar -r RUNTIME -m STREAM_VAR_MODEL_MAR -i INPUT_DATA_FILE -o OUTPUT_FILE
    required arguments:
        -r      Runtime (streamEngine)
        -i      Input File to be scored
        -o      Output File
        -m      StreamVar Model MAR
        -d      Driver Conf (required for streamEngine runtime)
    optional arguments:
        -h      Show this help message
        -x      Java heap memory

* This should run the model on the input dataset examples/input_with_var_requests.jsonl and write the output to output.jsonl

=== SVEXEC

.To run with Sv Executor

* Download the zip.
* Unzip the distribution(SE) using the following command

	unzip streamvar-mdk-svexec-<version>.zip

TIP: To execute scripts from anywhere, MDK directory can be added to the PATH variable.

* Build the Stream Var model against a pre-packaged example configuration/json dataset. To do so execute –

	bash build_mar -c examples/sv_dsl.csv.feature

    Command Line Arguments
    usage: bash build_mar -c <stream var config file>
    required arguments:
        -c      StreamVar Config File
    optional arguments:
        -h      Show this help message
        -m      StreamVar Model mar name
	
* This should build the Stream Var mar and place it your current directory. Default mar name is stream-var-model.mar
* You can create the model with different name by supplying the argument *-m <model name>* in the above command
* To run the Stream Var model against an input dataset

	bash execute_mar -r svExec -m stream-var-model.mar -i examples/input_with_var_requests.csv.jsonl -o output.jsonl

    Command Line Arguments
    usage: bash execute_mar -m STREAM_VAR_MODEL_MAR -i INPUT_DATA_FILE -o OUTPUT_FILE
    required arguments:
        -r      Runtime (svExec or streamEngine)
        -i      Input File to be scored
        -o      Output File
        -m      StreamVar Model MAR
        -d      Driver Conf (required for streamEngine runtime)
    optional arguments:
        -h      Show this help message
        -x      Java heap memory

* This should run the model on the input dataset *examples/input_with_var_requests.csv.jsonl* and write the output to *output.jsonl*

=== AW

.To run with AW

<< To be updated >>

//* Below is the link of notebook having all the instructions in it. Please import the notebook on aw. +
//https://fico.app.box.com/folder/61520581580[AW Reference Notebook] (current this link redirects to MDK releases box location)