---
title: "Field Validation"
linkTitle: "Field Validation"
date: 2017-02-05
description: >
  A short lead description about this content page. It can be **bold** or _italic_ and can be split over multiple paragraphs.
---
=== Field Validation : Errors and Warnings
Validation of the fields/variables can be performed by configuring the DSL statements.


CAUTION: Stream var supports validation of only Boolean fields +
Boolean fields can be prepared using the stateless operation

. *Error* : This will terminate the further processing of the transaction +
    So, if the error occurs for pre processing variable then profile update will not happen for this transaction.
. *Validation*: This will accumulate all the warnings for the given transaction and print that along with output response.

IMPORTANT: Error validation can be done on pre processed variables and variables that are calculated before the profile update happens +
 Warning validation can be done on any variables. +
 Validation is not supported for cross profile variables.

Following options are available.

==== Error/Warning DSL statements with inline error message

[source,gherkin]
-------
Variable Set:
Validate conditions when the input data source is "<datasoruce>"
With warning "<warning_code>" with message "<error_message>" if "<field_to_validate>" is <true|false>
With error "<error_code>" with message "<error_message>" if "<field_to_validate>" is <true|false>
-------

Example
[source,gherkin]
-------
Variable Set:
Validate conditions when the input data source is "Accounts"
With warning "101" with message "transaction amount is too high" if "amountGt500" is true
With error "102" with message "high value merchantType" if "merchantTypeLuxuaryAndAmountGt500" is true
-------


==== Configuring the error code and description mapping in DSL

[source,gherkin]
-------
Variable Set:
Validate conditions when the input data source is "<datasoruce>"
With warning "<warning_code>" if "<field_to_validate>" is <true|false>
With error "<error_code>" if "<field_to_validate>" is <true|false>
With error code descriptions as below
| error_code   | message              |
| <error_code> | <error_message>      |
With warning code descriptions as below
| warning_code  | message             |
| <warning_code | <warning_message>   |
-------

Example
[source,gherkin]
-------
Variable Set:
Validate conditions when the input data source is "Accounts"
With warning "101" if "amountGt500" is true
With error "102" if "merchantTypeLuxuaryAndAmountGt500" is true
With error code descriptions as below
| error_code | message                        |
| 102        | High expenditure merchant type |
With warning code descriptions as below
| warning_code | message                                |
| 101          | The amount is too high         |
-------

NOTE:

* If the error code mapping is specified inline than that takes preference over the DSL code mapping table.
* If the error code mapping is not specified (neither inline nor through the mapping table), default message will be printed as "<field_to_validate> is <true|false>"


==== Field validation using Custom functions
For complex error and warning validation, custom function can be written in kotlin

.Here are three options
1. Function returning only list of warning ```List<Warning>```
 2. Function returning only list of error ```List<Error>```
 3. Function returning pair with list of error and warning  ```Pair<List<Error>,List<Warning>>```


[source,gherkin]
-------
Variable Set:
Validate conditions when the input data source is "<datasoruce>"
With warnings using "<function_name>" function from "<script_path>" with arguments "argument1, arugument2,.."
With errors using "<function_name>" function from "<script_path" with arguments "argument1, arugument2,.."
With errors and warnings using "<function_name>" function from "<script_path" with arguments "argument1, arugument2,.."
-------

Example
[source,gherkin]
-------
Variable Set:
    Validate conditions when the input data source is "Accounts"
With warnings using "warnFunction" function from "examples/example-udfs.kt" with arguments "avg_spend_on_luxuary_4_days,min_spend_on_luxuary_4_days"
With errors using "errorFunction" function from "examples/example-udfs.kt" with arguments "avg_spend_on_luxuary_4_days,max_spend_on_luxuary_4_days"
With errors and warnings using "validateForErrorsAndWarnings" function from "examples/example-udfs.kt" with arguments "date,lastTransactionDate,5,amount,lastTxnAmount,merchantcode"
-------


.Argument can also be supplied using named argument approach as discussed following -

[source,gherkin]
-------
Variable Set:
Validate conditions when the input data source is "<datasource>"
With warnings using "<function>" function from "<script_path>" with arguments as below
| argument_name         | argument_value    |
| <parameter_name>      | <parameter_value> |
-------

Example
[source,gherkin]
-------
Variable Set:
Validate conditions when the input data source is "Merchants"
With warnings using "warnFunction" function from "examples/example-udfs.kt" with arguments as below
| argument_name | argument_value            |
| avgValue      | averageSpendFromVISA4days |
| minValue      | minSpendFromVISA4days     |
-------

Sample UDFs :

IMPORTANT: UDFs for field validation can only return List<com.fico.streamengine.api.record.Warning>,List<com.fico.streamengine.api.record.Error> or Pair<List<com.fico.streamengine.api.record.Warning>,List<com.fico.streamengine.api.record.Error>>.

[source,kotlin]
-----
include::code/example-udfs.kt[tag=warn]
-----

[source,kotlin]
-----
include::code/example-udfs.kt[tag=error]
-----

[source,kotlin]
-----
include::code/example-udfs.kt[tag=errorandwarn]
-----

Sample Output with errors and warnings:

[source,json]
----
{"recordName":"Accounts:VariableResponse","payloadString":"true,false,false,false,false,1/1/2006 01:00:55,0.0,NaN,NaN,0.0,,0.0,10,Accounts,A_2","warnings":[{"code":101,"message":"The amount is too high"}]}

{"recordName":"ErrorResponse","errors":[{"code":103,"message":"expenditure on luxury"}]}

{"recordName":"ErrorResponse","warnings":[{"code":101,"message":"The amount is too high"},{"code":102,"message":"High expenditure merchant type"}],"errors":[{"code":103,"message":"expenditure on luxury"}]}

----