[[input-set]]
=== Input Set
Schema of the input data record/Information Request record is provided in this section.

Sample config for Mutating/Input data record
[source,gherkin]
----
include::code/sample.feature[tag=inputset]
----

[[datatypes]]
*List of supported data types* : Here is the list of all the supported data types -

* BOOLEAN
* STRING
* INT
* LONG
* FLOAT
* DOUBLE
* BIGDECIMAL
* BIGINTEGER

*Data Source*: To specify the data source name of the input data record.

[source,gherkin]
----
include::code/sample.feature[tag=datasource]
----

*Input Format*: Here, format of the StreamVar input needs to be specified. Note that supported input formats are CSV, JSON

[source,gherkin]
----
include::code/sample.feature[tag=input]
----
Detailed description <<input_records,here>>

*Input Data Layout*: To specify the input data schema (provide field names under field_name and type of the fields under data_type)
[NOTE]
Order of the field matters in case of CSV, however for JSON it can be in any order.

[source,gherkin]
----
include::code/sample.feature[tag=inputfields]
----

Sample config for Non-mutating/Information Request record
[source,gherkin]
----
include::code/sample.feature[tag=inputsetnonmutating]
----