=== Null/Missing value handling

Stream var doesn't allow *null* values. Any input field with null value will result in an error.
In case these null values needs to handled in stream var then default value for each of the fields needs to be configured.
To configure the default values provide the value in the *default_value* column along with input fields.
Default value should be provided for all the fields that may contain null otherwise left empty.

IMPORTANT: All missing tags are treated same as null values.

    Input Set:
    Given input data source "Accounts"
    And input formatted as "json"
    With fields
    | field_name                           | data_type | default_value|
    | accountid                            | String    | "foo"        |
    | merchantcode                         | Int       | 100          |
    | amount                               | Double    | 100.0        |
    | date                                 | String    |              |
    | merchantType                         | String    |              |
    | nonWorkingHoursSpendingOnMerchandise | String    |              |

