=== Quantile Estimation(QE) using DSL
Following QE Variable functions can be used in the DSL to generate the QE variables

1. Scale value of the observation
2. Quantile estimate at the given quantile value
3. Log-odds of estimated cumulative probability

Calculation of the QE is a three step process.

==== Defining the profile
===== To Declare the QE Profile
[source,gherkin]
-------
include::code/qe-variables.feature[tag=qe-profile-declaration]
-------

===== Defining the peer group property

peer group property for the profile can be configured using the DSL statement below
[source,gherkin]
-------
include::code/qe-variables.feature[tag=peer-group-property]
-------

peer group property field cn be any of the input fields/ input field derived stateless variables or constant. Constant needs to be enclosed in single quotes wrapped in double quotes.

NOTE: This property is optional and the default value is '' ( empty string) that will lead to no peer grouping.


===== Defining the merge period

merge period for the profile can be configured using the DSL statement below
[source,gherkin]
-------
include::code/qe-variables.feature[tag=merge-period-property]
-------
NOTE: This property is optional and the default value is 0 that will disable the merging

===== Defining the Shuffler function

Shuffler for the profile can be configured using the DSL statement below
[source,gherkin]
-------
include::code/qe-variables.feature[tag=shuffler-property]
-------
NOTE: This property is optional and the default value is "RandomPermutation" that will disable the merging

.Supported shuffler functions are
1. Hash
2. RandomPermutation
3. RoundRobin


===== Defining the number of partitions for the profile (number of threads)

Number of partitions for the profile can be configured using the DSL statement below
[source,gherkin]
-------
include::code/qe-variables.feature[tag=partitions-property]
-------
NOTE: This property is optional and the default value is 1.

===== Complete config with merge period, peer group, shuffler and number of partitions

[source,gherkin]
-------
include::code/qe-variables.feature[tag=complete-qe-profile]
-------

==== Defining the QE function and function parameters

[source, gherkin]
-----
include::code/qe-variables.feature[tag=qe-param-declaration]
-----

.Supported QE functions are
1. legacyFalcon
2. adaptiveGridEventDecay
3. adaptiveTierney

==== Defining the variables

Multiple QEs of the same type for different variables can be generated by adding a separate line for each variable
Example
[source, gherkin]
-----
include::code/qe-variables.feature[tag=qe-variable-generation]
-----

Some properties can be overridden at variable level as in the above example for "qeEventAvgTierney"

Here "qeEventAvgTierney" will be calculated as the scaled value of "account_amount:merchantIsCash_Yes:event_avg_4D" with qLow as 0.95, qHigh as 0.99 and eventScale "1000"

Conditional update of QE is possible with additional "updateWhen" parameter, this can take any field of type Boolean(this will update the profile only when the boolean field has value true)
[source, gherkin]
-----
| param_name        | param_value    |
| updateWhen        | merchantIsCash |

-----

==== QE Variables
[[QE_scaled_vale]]
===== Scaled Value calculation
[source, gherkin]
-----
include::code/qe-variables.feature[tag=scaled_qe]
-----

[[Log-odds]]
===== Log-odds of estimated cumulative probability
log-odds of estimated cumulative probability, i.e given x, return logodds(p); p = P(X <= x)}
[source, gherkin]
-----
include::code/qe-variables.feature[tag=log-odds]
-----

[[quantile_estimate]]
===== Value Estimation at given quantile
quantile estimate x, such that CDF(X=x) = q
[source, gherkin]
-----
include::code/qe-variables.feature[tag=quantileEstimate]
-----

.Here are the following points about QE.
1. Each QE profile will run in a separate model step with number of threads equals the number of partitions configured for this profile( default is 1).
2. QE model step will be triggered after the Simple profile update steps. Hence QE variable can not be used in any other profiled variables.
3. Peer group field can also be prepared using stateless operations.
4. One QE profile can contain any number of QEs(also of different QE type) with the same peer group string.
5. Calculation happens before the current observation is updated in the profile.





