[[scoring-model]]

The StreamVar MDK supports feed forward network scoring in the model flow through the SV DSL language specification.

Below is the sample configuration that will enable the scoring in the model workflow.

[source,gherkin]
----
include::code/sample.feature[tag=scoring]
----

Here the “examples/scoring.conf” is configurable. The required scoring conf can be provided here. “value_name” column specifies the features that are to be used in score calculation. Features can be input fields, prepared fields (on intermediate fields) or profiled variables.

NOTE: Features are passed to the scoring step in the same order defined in *value_name*

IMPORTANT: Currently the StreamVar model doesn’t support nesting of files in the scoring conf. i.e. scoring conf has to be complete in itself, no external path inclusion is supported.

Scoring conf is packaged in the generated *jar/mar*. Any changes in the config file will require rebuilding the artifact.

Example feature file is included with the package *examples/sv_dsl.json.everyinput.feature* and example scoring.conf is included with the package examples/scoring.conf

NOTE: This feature file only demonstrate the gherkins statement, it might not have a sensible scoring configuration

**Conditional Scoring**

Stream Var supports conditional scoring, i.e, Scores can be generated based on some event.
Here is the example of conditional scoring

[source,gherkin]
----
include::code/sample.feature[tag=conditional_scoring]
----

**Segmented Scoring**

Along with the conditional score, the segmented scoring can also be achieved with StreamVar.
Here the based on the given condition appropriate scoring will happen the score will be produced.

here is the example for the segmented scoring.

[source,gherkin]
----
include::code/sample.feature[tag=segmented_scoring]
----


[[reason-model]]
The MDK also supports integrating the Falcon Reason Reporter reason model in the model flow along with scoring. The sample configuration below will enable reason code evaluation in addition to the score.


[source,gherkin]
----
include::code/sample.feature[tag=reasons]
----

Here "examples/reasons.conf" is configurable. The required reason conf can be provided here. The reason model uses the same set of features, in the same order, as the score calculator.

The format for json payload with score and reasons is as follows
[source,json
----
{"recordName":"Accounts:ScoreResponse","payload":{"account_amount:merchantIsCash_Yes:event_avg_1D":0.0,"account_amount:all:min_1D":334.6402817395708,"account:luxuryOrAirlineGt500_No:freq_2D":1,"account:nonWorkingHoursSpendingOnMerchandise:min_delta_time_1D":0,"account:merchantIsCash_Yes:recency_1D":-1,"account_amount:luxuryOrAirlineGt500_Yes:min_30D_7L::account_amount:luxuryOrAirlineGt500_Yes:max_30D_7L":"NaN","account_merchantcode:all:blist_is_miss_5L":true,"binnedAmount":0,"amountEqualTo10":false,"amountGreaterThan12":true,"amountPlus10":344.6402817395708,"amount1PlusAmount2":1520,"amount1MultiplyAmount2":41830.03521744635,"countryWOE":1.045857,"postLookup":0.015593,"__score__":15.748311374054328,"__reasons__":[{"reasonCode":"101","reasonContribution":14.828311374054328,"reasonDescription":"Average amount spent on cash transactions is too high","inputFeature":"account_amount:nonWorkingHoursSpendingOnMerchandise_Y:min_4D_cond"},{"reasonCode":"102","reasonContribution":14.828311374054328,"reasonDescription":"Amount spent during non-working hours is too high","inputFeature":"account:luxuryOrAirlineGt500_No:freq_4D_cond"},{"reasonCode":"104","reasonContribution":14.828311374054328,"reasonDescription":"The smallest time gap between two transactions during non working hours is suspicious","inputFeature":"account:merchantIsCash_Yes:recency_4D_cond"}],"__inputRecordName__":"Accounts","account:__profileKey__":"A_14","account:__profileAccessTime__":"1/1/2006 01:00:55"}}
----

By default all the reason codes will be printed. If you want to limit the number of reason codes , then the same can be configured in the dsl

[source,gherkin]
----
include::code/sample.feature[tag=limited_reasons]
----

Example feature file is included with the package *examples/sv_dsl.json.everyinput.feature* and example scoring.conf is included with the package examples/reasons.conf

**Segmented reason**

Similar to segmented scoring, the reason code for the segmented score can also be generated using the sample DSL statement as below

[source,gherkin]
----
include::code/sample.feature[tag=segmented_reasons]
----