=== Stateless Variables
*Pre-processed/Post-processed Variable Config*

This is to generate additional variables before and/or after profile update using Arithmetic, Logical , String Concatenation and Ternary operations on input fields/profile variables/any other pre/post processed variables.
These variables comes under the Variable Set section.

[NOTE]
Only one operation per line is supported.

To specify the data source for which fields need to be prepared.

[source,gherkin]
----
include::code/sample.feature[tag=variablesetsource]
----

Following operations are supported for field generation –

*   Logical Operations
*   Arithmetic operations
*   Ternary Operation
*   Constant Assignment Operation
*   Concatenation Operation
*   <<udfs,Custom functions written in Koltin>>

----
include::code/sample.feature[tag=preparedstmt]

----
[NOTE]
=========================
*   If the operand is String literal, then it has to enclosed in single quotes wrapped in double quotes.
*   If operand is field, then in has to be enclosed in double quotes.
*   Numerical literal should be written as it is. (no double/single quotes required)
=========================

List of supported operations can be found <<pre-post-processed-variables,here>>

[[ratio-variable-config]]
=== Ratio Variable Config
This section is to specify the ratio variables. Numerator variables and denominator variables along with the filter strategy need to be provided.
These variables also comes under the Variable Set section.

* *numerator* – function to use on parameter set and then use the resultant variable as numerator.
* *param_set_num* – parameter set name on which the Numerator function is to be applied.
* *denominator* – function to use on parameter set and then use the resultant variable as denominator
* *param_set_den* – parameter set name on which the Denominator function is to be applied

*Filter Strategy* => StreamVar provides two filter strategy for ratio variables.

1. full - [red]*todo*
2. diagonal - [red]*todo*

[source,gherkin]
----
include::code/sample.feature[tag=ratio]
----