[[udfs]]
=== Custom functions for Pre/Post processing
StreamVar provides support for custom functions to be executed for calculation of pre(and post) processing of variables.
Custom functions can be written in https://kotlinlang.org/docs/reference/[kotlin] language.

Below are some rules for writing the Kotlin script with Custom functions for StreamVar. +

. File must have the https://kotlinlang.org/docs/reference/packages.html#packages[package] name. You can give the default package name(*"com.fico.analytics.aarf.udfs"*)
. Method should be stateless i.e method should depend on only on the input parameters.
. Only Primitives(and wrapper classes) data types are supported as input and output.

Here is the sample koltin file say "example-udfs.kt"

[source,kotlin]
-------
include::code/example-udfs.kt[]
-------

Here are two options to call the sum function as part of the StreamVar pre or post processing of variables.

*Option 1* : With ordered arguments +
Here the function arguments need to be passed in order of their declaration in the method signature. +

Sample gherkin config

[source,gherkin]
-------
 With "<var_name>" of type "<return_type_of_function>" as the value of the "<package_name>.<function_name>" function from "<kotlin_ile_path>" with arguments "<argument1><argument1>...<argumentn>"
-------

Example :

[source,gherkin]
-------
 With "sum_of_2_num" of type "double" as the value of the "com.fico.analytics.aarf.udfs.sum" function from "examples/example-udfs.kt" with arguments "amount,10"
-------

In the above example 'amount' will be assigned to parameter 'a' and 10 will be assigned to parameter 'b'

Note : In the above example package name(*"com.fico.analytics.aarf.udfs"*) is optional as it is same as default package used by StreamVar. Hence following will also work.

[source,gherkin]
-------
 With "sum_of_2_num" of type "double" as the value of the "sum" function from "examples/example-udfs.kt" with arguments "amount,10"
-------

[[Custom-functions-with-named-args]]
*Option 2* : With named arguments +
Here the function arguments can to be passed as key value. Arguments need not be in order +

Sample gherkin config
[source,gherkin]
-------
  With "<var_name>" of type "<return_type_of_function>" as the value of the "<package_name>.<function_name>" function from "<kotlin_ile_path>" with arguments as below
    |argument_name       | argument_value     |
    |<argument1_name>    | <argument1_value>  |
    |<argument2_name>    | <argument2_value>  |
    .
    .
    .
    |<argumentn_name>    | <argumentn_value>  |

-------

Example :

[source,gherkin]
-------
  With "sum_of_2_num" of type "double" as the value of the "sum" function from "examples/example-udfs.kt" with arguments as below
    |argument_name  | argument_value |
    |a              | amount         |
    |b              | 100.0          |

-------