[big]*A. StreamVar Variables dependant on numeric field, category field and category value*

Below is a sample gherkin configuration for minimum_by_category for "account" profile when data source is “Accounts"

[source,gherkin]
----
include::code/sample.feature[tag=variableexplosion_a]
----

This configuration will calculate – minimum amount when merchantTypeIsCash is Yes(and No) in last 1(and 2) discrete time (for ex. Days). Below are the exact variable names that will get generated in the output file.

    account_amount:merchantIsCash_Yes:min_1D:Double
    account_amount:merchantIsCash_No:min_1D:Double
    account_amount:merchantIsCash_Yes:min_2D:Double
    account_amount:merchantIsCash_No:min_2D:Double

Following variables can be generated using the same configuration –

	MINIMUM_BY_CATEGORY
	MAXIMUM_BY_CATEGORY
	SUM_BY_CATEGORY
	STDDEV_BY_CATEGORY
	TIME_AVERAGE_BY_CATEGORY
	EVENT_AVERAGE_BY_CATEGORY

[big]*B. StreamVar Variables dependant on numeric field*

Below is sample gherkin configuration for "account" profile when data source is “Accounts"

[source,gherkin]
----
include::code/sample.feature[tag=variableexplosion_b]
----

This configuration will calculate – overall minimum amount for merchantTypeIsCash in last 1(and 2) discrete time (for ex. Days).

NOTE: categorical filters are not needed for this variable class.

Below are the exact variable names which you will get in the output file.

    account_amount:all:min_1D:Double
    account_amount:all:min_2D:Double

Following variables can be generated using the same configuration –

	OVERALL_MINIMUM
	OVERALL_MAXIMUM
	OVERALL_SUM
	OVERALL_STDDEV
	OVERALL_TIME_AVERAGE
	OVERALL_EVENT_AVERAGE

[big]*C. StreamVar Variables dependant on category field and category values*

Below is sample gherkin configuration for "account" profile when data source is “Accounts"

[source,gherkin]
----
include::code/sample.feature[tag=variableexplosion_c]
----

This configuration will calculate –  Number of discrete time when merchantTypeIsCash was Yes(and No) last.

NOTE: Numerical_field is not needed for this variable class. 

Below are the exact variable names which you will get in the output file.

    account:merchantIsCash_Yes:recency_1D:Double
    account:merchantIsCash_No:recency_1D:Double
    account:merchantIsCash_Yes:recency_2D:Double
    account:merchantIsCash_No:recency_2D:Double

Following variables can be generated using the same configuration –

    FREQUENCY_BY_CATEGORY
	RECENCY_BY_CATEGORY 
	PENULTIMATE_RECENCY_BY_CATEGORY
	MAXIMUM_CONSECUTIVE_STREAK_BY_CATEGORY
	MINIMUM_CONSECUTIVE_STREAK_BY_CATEGORY
	MAXIMUM_DELTA_TIME_BY_CATEGORY
	MINIMUM_DELTA_TIME_BY_CATEGORY
	AVERAGE_DELTA_TIME_BY_CATEGORY
	RECENT_CONSECUTIVE_STREAK_BY_CATEGORY
	PERIODS_WITH_OCCURRENCE_BY_CATEGORY

[big]*D. StreamVar Variables dependant on category field*

Below is sample gherkin configuration for "account" profile when data source is “Accounts"

[source,gherkin]
----
include::code/sample.feature[tag=variableexplosion_d]
----

This configuration will calculate –  Number of discrete time for merchantTypeIsCash.

NOTE: value_of_interest (category_value) is redundant for this variable class. Any value provided here will be ignored for this variable calculation. Numerical field is not needed for this variable class.

Below are the exact variable names which you will get in the output file.

    account:merchantIsCash:recency_1D:Double
    account:merchantIsCash:recency_2D:Double

Following variables can be generated using the same configuration –

    OVERALL_FREQUENCY
	OVERALL_PENULTIMATE_RECENCY
	OVERALL_MAXIMUM_CONSECUTIVE_STREAK
	OVERALL_MINIMUM_CONSECUTIVE_STREAK
	OVERALL_MAXIMUM_DELTA_TIME
	OVERALL_MINIMUM_DELTA_TIME
	OVERALL_AVERAGE_DELTA_TIME
	OVERALL_RECENT_CONSECUTIVE_STREAK
	OVERALL_PERIODS_WITH_OCCURRENCE
	OVERALL_RECENCY
	UNIQUE_VALUES_COUNT
	LATEST_VALUE_FOR_FIELD


